name: Deploy Script to Bunny
author: Bunny Devs
description: Use this action to upload an EdgeScript to your Bunny Pullzone.

inputs:
  script_id:
    description: The ScriptID associated to your Pullzone.
    required: true

  api_key:
    description: The API key for Bunny.
    required: false

  deploy_key:
    description: The associated DeployKey for Bunny.
    required: false

  file:
    description: The file path for the script.
    required: true

  base:
    description: The API endpoint - Only used for debug
    required: false
    default: "https://api.bunny.net"

runs:
  using: "node20"
  main: ".lib-action/index.js"

branding:
  color: "orange"
  icon: "upload-cloud"
